### ISSUE TITLE
Format date to be more readable

### ISSUE THREAD

**Issue by notionparallax** [BaptisteHiggs/BVN_Office_Staging#1]
is currently `Tue Aug 01 2017 00:00:00 GMT+1000 (AUS Eastern Standard Time)` should probably be something like `Tuesday 1st August`

Use moment.js maybe?

**Comment by BaptisteHiggs** [comment]
Date has been reformatted using moment.js to the above format ('MMMM Do YYYY')

**Comment by BaptisteHiggs** [comment]
Date has been reformatted using moment.js to the above format ('MMMM Do YYYY')
