### ISSUE TITLE
make page respond to screen size

### ISSUE THREAD

**Issue by notionparallax** [BaptisteHiggs/BVN_Office_Staging#3]
As a minimal first pass:

- [ ] make the left and right margins be zero and make the title smaller
- [ ] make the touch-target on the slider bigger

![image](https://user-images.githubusercontent.com/1865196/32419753-58adcad2-c2d3-11e7-86e7-f750ca6f7975.png)

**Comment by BaptisteHiggs** [comment]
Now reacts to screen size changes much more naturally. Leaving it unclosed as this is fairly subjective.

**Comment by BaptisteHiggs** [comment]
Grid css implemented, smooth changing between various screen size states
